{
 "title": "Go-Ethereum-By-Instance-PATH",
 "description": "A Prometheus metric dashboard for go-ethereum",
 "time": { "from": "2025-04-14T14:26:09.504Z", "to": "2025-04-14T16:12:03.318Z" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "label": "chain",
    "query": {
     "query": "label_values(chain_head_block{}, chain)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(chain_head_block{chain=~\"$chain\"}, instance)"
    }
   },
   {
    "name": "quantile",
    "query": "0.5, 0.75, 0.95, 0.99, 0.999, 0.9999"
   }
  ]
 },
 "panels": [
  {
   "title": "Blockchain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest header",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_header{chain=\"$chain\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Chain head",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "chain_head_header{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "header"
    },
    {
     "expr": "chain_head_receipt{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "receipt"
    },
    {
     "expr": "chain_head_block{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "block"
    }
   ]
  },
  {
   "title": "Chain Reorg Add",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_reorg_add{chain=\"$chain\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Block processing(q=$quantile) by mean",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "chain_execution{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "execution"
    },
    {
     "expr": "chain_validation{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "validation"
    },
    {
     "expr": "chain_write{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "chain write"
    },
    {
     "expr": "chain_account_reads{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account read"
    },
    {
     "expr": "chain_account_updates{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account update"
    },
    {
     "expr": "chain_account_hashes{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account hash"
    },
    {
     "expr": "max(chain_account_commits{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"} or chain_storage_commits{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"})",
     "legendFormat": "state commit"
    },
    {
     "expr": "chain_storage_reads{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "storage read"
    },
    {
     "expr": "chain_storage_updates{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "storage update"
    },
    {
     "expr": "chain_snapshot_commits{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "snapshot commit"
    }
   ]
  },
  {
   "title": "Block processing(q=$quantile) by last",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_execution{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "execution"
    },
    {
     "expr": "chain_validation{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "validation"
    },
    {
     "expr": "chain_write{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "chain write"
    },
    {
     "expr": "chain_account_reads{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account read"
    },
    {
     "expr": "chain_account_updates{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account update"
    },
    {
     "expr": "chain_account_hashes{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account hash"
    },
    {
     "expr": "max(chain_account_commits{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"} or chain_storage_commits{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"})",
     "legendFormat": "state commit"
    },
    {
     "expr": "chain_storage_reads{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "storage read"
    },
    {
     "expr": "chain_storage_updates{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "storage update"
    },
    {
     "expr": "chain_snapshot_commits{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "snapshot commit"
    }
   ]
  },
  {
   "title": "Latest block",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_block{chain=\"$chain\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Chain Reorg Drop",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_reorg_drop{chain=\"$chain\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Chain inserting(q=$quantile)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "chain_inserts{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "insert"
    }
   ]
  },
  {
   "title": "Block processing(q=$quantile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "chain_execution{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "execution"
    },
    {
     "expr": "chain_validation{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "validation (q=$quantile)"
    },
    {
     "expr": "chain_write{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "chain commit"
    },
    {
     "expr": "chain_account_reads{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account read"
    },
    {
     "expr": "chain_account_updates{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account update"
    },
    {
     "expr": "chain_account_hashes{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account hash"
    },
    {
     "expr": "chain_account_commits{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account commit"
    },
    {
     "expr": "chain_storage_reads{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "storage read"
    },
    {
     "expr": "chain_storage_updates{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "storage update"
    },
    {
     "expr": "chain_storage_commits{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "storage commit"
    },
    {
     "expr": "chain_snapshot_commits{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "snapshot commit"
    }
   ]
  },
  {
   "title": "Block processing(q=$quantile)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "chain_execution{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "execution"
    },
    {
     "expr": "chain_validation{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "validation"
    },
    {
     "expr": "chain_write{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "chain write"
    },
    {
     "expr": "chain_account_reads{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account read"
    },
    {
     "expr": "chain_account_updates{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account update"
    },
    {
     "expr": "chain_account_hashes{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account hash"
    },
    {
     "expr": "chain_account_commits{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account commit"
    },
    {
     "expr": "chain_storage_reads{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "storage read"
    },
    {
     "expr": "chain_storage_updates{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "storage update"
    },
    {
     "expr": "chain_storage_commits{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "storage commit"
    },
    {
     "expr": "chain_snapshot_commits{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "snapshot commit"
    }
   ]
  },
  { "title": "State Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Diff Layer cache hit%",
   "type": "timeseries",
   "description": "128 blocks in memory",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "state_snapshot_dirty_account_hit{chain=\"$chain\", instance=~\"$instance\"}/(state_snapshot_dirty_account_hit{chain=\"$chain\", instance=~\"$instance\"}+state_snapshot_dirty_account_miss{chain=\"$chain\", instance=~\"$instance\"})",
     "legendFormat": "account"
    },
    {
     "expr": "state_snapshot_dirty_storage_hit{chain=\"$chain\", instance=~\"$instance\"}/(state_snapshot_dirty_storage_hit{chain=\"$chain\", instance=~\"$instance\"}+state_snapshot_dirty_storage_miss{chain=\"$chain\", instance=~\"$instance\"})",
     "legendFormat": "storage"
    },
    {
     "expr": "pathdb_dirty_node_hit{chain=\"$chain\", instance=~\"$instance\"}/(pathdb_dirty_node_hit{chain=\"$chain\", instance=~\"$instance\"}+pathdb_dirty_node_miss{chain=\"$chain\", instance=~\"$instance\"})",
     "legendFormat": "trienode"
    }
   ]
  },
  {
   "title": "Bloom Filter TrueHit%",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "state_snapshot_bloom_account_truehit{chain=\"$chain\", instance=~\"$instance\"} / (state_snapshot_bloom_account_truehit{chain=\"$chain\", instance=~\"$instance\"} + state_snapshot_bloom_account_falsehit{chain=\"$chain\", instance=~\"$instance\"})",
     "legendFormat": "account"
    },
    {
     "expr": "state_snapshot_bloom_storage_truehit{chain=\"$chain\", instance=~\"$instance\"} / (state_snapshot_bloom_storage_truehit{chain=\"$chain\", instance=~\"$instance\"} + state_snapshot_bloom_storage_falsehit{chain=\"$chain\", instance=~\"$instance\"})",
     "legendFormat": "storage"
    }
   ]
  },
  {
   "title": "Disk Layer cache hit%",
   "type": "timeseries",
   "description": "backed by fastcache",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "state_snapshot_clean_account_hit{chain=\"$chain\", instance=~\"$instance\"}/(state_snapshot_clean_account_hit{chain=\"$chain\", instance=~\"$instance\"}+state_snapshot_clean_account_miss{chain=\"$chain\", instance=~\"$instance\"})",
     "legendFormat": "account"
    },
    {
     "expr": "state_snapshot_clean_storage_hit{chain=\"$chain\", instance=~\"$instance\"}/(state_snapshot_clean_storage_hit{chain=\"$chain\", instance=~\"$instance\"}+state_snapshot_clean_storage_miss{chain=\"$chain\", instance=~\"$instance\"})",
     "legendFormat": "storage"
    },
    {
     "expr": "pathdb_clean_node_hit{chain=\"$chain\", instance=~\"$instance\"}/(pathdb_clean_node_hit{chain=\"$chain\", instance=~\"$instance\"}+pathdb_clean_node_miss{chain=\"$chain\", instance=~\"$instance\"})",
     "legendFormat": "trienode"
    }
   ]
  },
  {
   "title": "Bloom Filter FalseHit#",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(state_snapshot_bloom_account_falsehit{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "account"
    },
    {
     "expr": "rate(state_snapshot_bloom_storage_falsehit{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "storage"
    }
   ]
  },
  {
   "title": "Disk Layer cache usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "state_snapshot_cache_size{chain=\"$chain\", instance=~\"$instance\"}/state_snapshot_cache_capacity{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "used%"
    },
    {
     "expr": "state_snapshot_cache_size{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "state_snapshot_cache_capacity{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Bloom Filter Miss#",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(state_snapshot_bloom_account_miss{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "account"
    },
    {
     "expr": "rate(state_snapshot_bloom_storage_miss{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "storage"
    }
   ]
  },
  {
   "title": "PathDB cache usage",
   "type": "timeseries",
   "description": "backed by fastcache",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pathdb_snapshot_cache_size{chain=\"$chain\", instance=~\"$instance\"}/pathdb_snapshot_cache_capacity{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "used%"
    },
    {
     "expr": "pathdb_snapshot_cache_size{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "pathdb_snapshot_cache_capacity{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  { "title": "State Snapshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Account Read#",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(state_snapshot_dirty_account_hit{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "diff layer"
    },
    {
     "expr": "rate(state_snapshot_clean_account_hit{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "disk layer"
    },
    {
     "expr": "rate(state_snapshot_dirty_account_inex{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "diff inex"
    },
    {
     "expr": "rate(state_snapshot_clean_account_inex{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "disk inex"
    },
    {
     "expr": "rate(state_read_account_1{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "read 1"
    },
    {
     "expr": "rate(state_read_account_2{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "read 2"
    },
    {
     "expr": "rate(state_snapshot_clean_account_miss{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "rawdb"
    }
   ]
  },
  {
   "title": "Storage Read#",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(state_snapshot_dirty_storage_hit{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "diff layer"
    },
    {
     "expr": "rate(state_snapshot_clean_storage_hit{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "disk layer"
    },
    {
     "expr": "rate(state_snapshot_dirty_storage_inex{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "diff inex"
    },
    {
     "expr": "rate(state_snapshot_clean_storage_inex{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "disk inex"
    },
    {
     "expr": "rate(state_read_storage_1{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "read 1"
    },
    {
     "expr": "rate(state_read_storage_2{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "read 2"
    },
    {
     "expr": "rate(state_snapshot_clean_storage_miss{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "rawdb"
    }
   ]
  },
  {
   "title": "Account Read%",
   "type": "timeseries",
   "description": "Based on the state account read count",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(state_snapshot_dirty_account_hit{chain=\"$chain\", instance=~\"$instance\"}[1m])/rate(state_read_account{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "diff layer"
    },
    {
     "expr": "rate(state_snapshot_clean_account_hit{chain=\"$chain\", instance=~\"$instance\"}[1m])/rate(state_read_account{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "disk cache"
    },
    {
     "expr": "rate(state_snapshot_clean_account_miss{chain=\"$chain\", instance=~\"$instance\"}[1m])/rate(state_read_account{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "disk rawdb"
    }
   ]
  },
  {
   "title": "Storage Read%",
   "type": "timeseries",
   "description": "Based on the state storage read count",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(state_snapshot_dirty_storage_hit{chain=\"$chain\", instance=~\"$instance\"}[1m])/rate(state_read_storage{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "diff layer"
    },
    {
     "expr": "rate(state_snapshot_clean_storage_hit{chain=\"$chain\", instance=~\"$instance\"}[1m])/rate(state_read_storage{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "disk cache"
    },
    {
     "expr": "rate(state_snapshot_clean_storage_miss{chain=\"$chain\", instance=~\"$instance\"}[1m])/rate(state_read_storage{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "disk rawdb"
    }
   ]
  },
  { "title": "StateDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "State",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(state_read_account{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "read account"
    },
    {
     "expr": "rate(state_read_storage{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "read storage"
    },
    {
     "expr": "rate(state_update_account{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "update account"
    },
    {
     "expr": "rate(state_update_storage{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "update storage"
    },
    {
     "expr": "rate(state_update_accountnodes{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "update account nodes"
    },
    {
     "expr": "rate(state_update_storagenodes{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "update storage nodes"
    },
    {
     "expr": "rate(state_delete_account{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "delete account"
    },
    {
     "expr": "rate(state_delete_storage{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "delete storage"
    },
    {
     "expr": "rate(state_delete_accountnodes{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "delete account nodes"
    },
    {
     "expr": "rate(state_delete_storagenodes{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "delete storage nodes"
    }
   ]
  },
  {
   "title": "Prefetch(block)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(chain_prefetch_executes_count{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "executes"
    },
    {
     "expr": "rate(chain_prefetch_interrupts{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "interrupts"
    },
    {
     "expr": "rate(chain_prefetch_txs_valid{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "valid tx"
    },
    {
     "expr": "rate(chain_prefetch_txs_invalid{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "invalid tx"
    }
   ]
  },
  {
   "title": "Prefetch(trie)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(trie_prefetch_chain_account_load_write{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "account load"
    },
    {
     "expr": "rate(trie_prefetch_chain_account_dup_write{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "account dup"
    },
    {
     "expr": "rate(trie_prefetch_chain_storage_load_write{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "storage load"
    },
    {
     "expr": "rate(trie_prefetch_chain_storage_dup_write{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "storage dup"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "chain_account_reads{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account read (q=$quantile)"
    },
    {
     "expr": "chain_account_updates{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account update (q=$quantile)"
    },
    {
     "expr": "chain_account_commits{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account commit (q=$quantile)"
    },
    {
     "expr": "chain_storage_reads{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "storage read (q=$quantile)"
    },
    {
     "expr": "chain_storage_updates{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "storage update (q=$quantile)"
    },
    {
     "expr": "chain_storage_commits{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "storage commit (q=$quantile)"
    },
    {
     "expr": "chain_snapshot_commits{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "snapshot commit (q=$quantile)"
    },
    {
     "expr": "chain_triedb_commits{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "triedb commit (q=$quantile)"
    }
   ]
  },
  {
   "title": "Read Single Latency(q=0.99)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "chain_account_single_reads{chain=\"$chain\", instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "account read"
    },
    {
     "expr": "chain_storage_single_reads{chain=\"$chain\", instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "storage read"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Data rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(eth_db_chaindata_disk_read{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "ethdb read"
    },
    {
     "expr": "rate(eth_db_chaindata_disk_write{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "ethdb write"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_read{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "ancient read"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_write{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "ancient write"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_input{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "compact read"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_output{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "compact write"
    }
   ]
  },
  {
   "title": "Session totals",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_disk_read{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "leveldb read"
    },
    {
     "expr": "eth_db_chaindata_disk_write{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "leveldb write"
    },
    {
     "expr": "eth_db_chaindata_ancient_read{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "ancient read"
    },
    {
     "expr": "eth_db_chaindata_ancient_write{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "ancient write"
    }
   ]
  },
  {
   "title": "Storage size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_disk_size{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "leveldb"
    },
    {
     "expr": "eth_db_chaindata_ancient_size{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "ancient"
    }
   ]
  },
  {
   "title": "Ethdb reqeusts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(eth_db_chaindata_write_count{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "write"
    },
    {
     "expr": "rate(eth_db_chaindata_read_existed_count{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "read 200"
    },
    {
     "expr": "rate(eth_db_chaindata_read_notfound_count{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "read 404"
    }
   ]
  },
  {
   "title": "Compact Writedelay Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_compact_writedelay_counter{chain=\"$chain\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Compact",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(eth_db_chaindata_compact_time{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "time"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_nonlevel0{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "levelN"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_level0{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "level0"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_memory{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "mem"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_seek{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "seek"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_writedelay_duration{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "delay time"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_writedelay_counter{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "delay count"
    }
   ]
  },
  {
   "title": "Compact Writedelay Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_compact_writedelay_duration{chain=\"$chain\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Ethdb latency($quantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_write_duration{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "write"
    },
    {
     "expr": "eth_db_chaindata_read_existed_duration{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "read 200"
    },
    {
     "expr": "eth_db_chaindata_read_notfound_duration{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "read 404"
    }
   ]
  },
  {
   "title": "Level Amp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_read_amp{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "read"
    },
    {
     "expr": "eth_db_chaindata_write_amp_level0{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "write0"
    },
    {
     "expr": "eth_db_chaindata_write_amp_level1{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "write1"
    },
    {
     "expr": "eth_db_chaindata_write_amp_level2{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "write2"
    },
    {
     "expr": "eth_db_chaindata_write_amp_level3{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "write3"
    },
    {
     "expr": "eth_db_chaindata_write_amp_level4{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "write4"
    },
    {
     "expr": "eth_db_chaindata_write_amp_level5{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "write5"
    },
    {
     "expr": "eth_db_chaindata_write_amp_level6{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "write6"
    }
   ]
  },
  {
   "title": "Compact",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(eth_db_chaindata_compact_count{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "count"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_read{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_move{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "move"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_multilevel{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "multilevel"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_counterlevel{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "counterlevel"
    },
    {
     "expr": "eth_db_chaindata_compact_inprogressbytes{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "inprogress"
    }
   ]
  },
  {
   "title": "Cache count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_blockcache_count{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "block cache count"
    },
    {
     "expr": "eth_db_chaindata_tablecache_count{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "table cache count"
    },
    {
     "expr": "eth_db_chaindata_blockcache_size{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "block cache size"
    },
    {
     "expr": "eth_db_chaindata_tablecache_size{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "table cache size"
    }
   ]
  },
  {
   "title": "Cache hit%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_blockcache_hits{chain=\"$chain\", instance=~\"$instance\"}/(eth_db_chaindata_blockcache_hits{chain=\"$chain\", instance=~\"$instance\"}+eth_db_chaindata_blockcache_miss{chain=\"$chain\", instance=~\"$instance\"})",
     "legendFormat": "block cache hit%"
    },
    {
     "expr": "eth_db_chaindata_tablecache_hits{chain=\"$chain\", instance=~\"$instance\"}/(eth_db_chaindata_tablecache_hits{chain=\"$chain\", instance=~\"$instance\"}+eth_db_chaindata_tablecache_miss{chain=\"$chain\", instance=~\"$instance\"})",
     "legendFormat": "table cache hit%"
    },
    {
     "expr": "eth_db_chaindata_filter_hits{chain=\"$chain\", instance=~\"$instance\"}/(eth_db_chaindata_filter_hits{chain=\"$chain\", instance=~\"$instance\"}+eth_db_chaindata_filter_miss{chain=\"$chain\", instance=~\"$instance\"})",
     "legendFormat": "filter hit%"
    }
   ]
  },
  {
   "title": "TxPool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 151 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executable transactions",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "txpool_pending{chain=\"$chain\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Transaction pool",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 3, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "txpool_pending{chain=\"$chain\", instance=~\"$instance\"}",
       "legendFormat": "executable"
      },
      {
       "expr": "txpool_queued{chain=\"$chain\", instance=~\"$instance\"}",
       "legendFormat": "gapped"
      },
      {
       "expr": "txpool_local{chain=\"$chain\", instance=~\"$instance\"}",
       "legendFormat": "local"
      }
     ]
    },
    {
     "title": "Transaction propagation",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(txpool_valid{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "valid"
      },
      {
       "expr": "rate(txpool_invalid{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "invalid"
      },
      {
       "expr": "rate(txpool_underpriced{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "underpriced"
      },
      {
       "expr": "rate(txpool_pending_discard{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "executable discard"
      },
      {
       "expr": "rate(txpool_pending_replace{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "executable replace"
      },
      {
       "expr": "rate(txpool_pending_ratelimit{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "executable ratelimit"
      },
      {
       "expr": "rate(txpool_pending_nofunds{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "executable nofunds"
      },
      {
       "expr": "rate(txpool_queued_discard{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "gapped discard"
      },
      {
       "expr": "rate(txpool_queued_replace{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "gapped replace"
      },
      {
       "expr": "rate(txpool_queued_ratelimit{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "gapped ratelimit"
      },
      {
       "expr": "rate(txpool_queued_nofunds{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "gapped nofunds"
      },
      {
       "expr": "rate(txpool_known{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "known"
      }
     ]
    },
    {
     "title": "Local transactions",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "txpool_local{chain=\"$chain\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Gapped transactions",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "txpool_queued{chain=\"$chain\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 152 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success RPC QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(geth_rpc_requests_success_count{instance=\"$instance\"}[5m])) by (chain, instance, method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Failure RPC QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(geth_rpc_requests_failure_count{instance=\"$instance\"}[5m])) by (chain, instance, method)",
       "legendFormat": "{{method}}"
      },
      {}
     ]
    },
    {
     "title": "Success RPC Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(geth_rpc_requests_success{quantile='$quantile', instance=\"$instance\"}[5m])) by (chain, instance, method) \n/ \nsum(rate(geth_rpc_requests_success_count{instance=\"$instance\"}[5m])) by (chain, instance, method) /1e6 \n< 1e200",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Failure RPC Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(geth_rpc_requests_failure{quantile='$quantile', instance=\"$instance\"}[5m])) by (chain, instance, method) / sum(rate(geth_rpc_requests_failure_count{instance=\"$instance\"}[5m])) by (chain, instance, method) /1e6",
       "legendFormat": "{{method}}"
      },
      {}
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(system_cpu_sysload{chain=\"$chain\", instance=~\"$instance\"}) by (instance)",
       "legendFormat": "system"
      },
      {
       "expr": "avg(system_cpu_syswait{chain=\"$chain\", instance=~\"$instance\"}) by (instance)",
       "legendFormat": "iowait"
      },
      {
       "expr": "avg(system_cpu_procload{chain=\"$chain\", instance=~\"$instance\"}) by (instance)",
       "legendFormat": "geth"
      },
      {
       "expr": "avg(system_cpu_goroutines{chain=\"$chain\", instance=~\"$instance\"}) by (instance)",
       "legendFormat": "goroutines"
      },
      {
       "expr": "avg(system_cpu_threads{chain=\"$chain\", instance=~\"$instance\"}) by (instance)",
       "legendFormat": "threads"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(system_memory_allocs{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "alloc"
      },
      {
       "expr": "system_memory_used{chain=\"$chain\", instance=~\"$instance\"}",
       "legendFormat": "used"
      },
      {
       "expr": "system_memory_held{chain=\"$chain\", instance=~\"$instance\"}",
       "legendFormat": "held"
      },
      {
       "expr": "rate(system_memory_frees{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "free"
      }
     ]
    },
    {
     "title": "Disk",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(system_disk_readbytes{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "read"
      },
      {
       "expr": "rate(system_disk_writebytes{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "write"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Traffic",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(p2p_ingress{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "ingress-rate"
      },
      {
       "expr": "rate(p2p_egress{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "egress-rate"
      },
      {
       "expr": "p2p_ingress{chain=\"$chain\", instance=~\"$instance\"}",
       "legendFormat": "igress-flow"
      },
      {
       "expr": "p2p_egress{chain=\"$chain\", instance=~\"$instance\"}",
       "legendFormat": "egress-flow"
      }
     ]
    },
    {
     "title": "Peers",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "p2p_peers{chain=\"$chain\", instance=~\"$instance\"}",
       "legendFormat": "peers"
      },
      {
       "expr": "rate(p2p_dials{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "dials"
      },
      {
       "expr": "rate(p2p_serves{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "serves"
      }
     ]
    },
    {
     "title": "P2P Handles",
     "type": "timeseries",
     "description": "# eth protocol\n\n- `0x00` = StatusMsg\n- `0x01` = NewBlockHashesMsg\n- `0x02` = TransactionsMsg\n- `0x03` = GetBlockHeadersMsg\n- `0x04` = BlockHeadersMsg\n- `0x05` = GetBlockBodiesMsg\n- `0x06` = BlockBodiesMsg\n- `0x07` = NewBlockMsg\n- `0x08` = NewPooledTransactionHashesMsg\n- `0x09` = GetPooledTransactionsMsg\n- `0x0a` = PooledTransactionsMsg\n- `0x0d` = GetNodeDataMsg\n- `0x0e` = NodeDataMsg\n- `0x0f` = GetReceiptsMsg\n- `0x10` = ReceiptsMsg\n\n# snap protocol\n\n- `0x00` = GetAccountRangeMsg\n- `0x01` = AccountRangeMsg\n- `0x02` = GetStorageRangesMsg\n- `0x03` = StorageRangesMsg\n- `0x04` = GetByteCodesMsg\n- `0x05` = ByteCodesMsg\n- `0x06` = GetTrieNodesMsg\n- `0x07` = TrieNodesMsg",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "label_replace(\n    label_replace({__name__=~\"p2p_handle_[a-z]+_[0-9]+_.*_count\", instance=~\"$instance\"}, \"protocol\", \"$1$2\", \"__name__\", \"p2p_handle_([a-z]+)_([0-9]+)_(.*)_count\"),\n    \"msgcode\", \"$3\", \"__name__\", \"p2p_handle_([a-z]+)_([0-9]+)_(.*)_count\")",
       "legendFormat": "{{protocol}}-{{msgcode}}"
      }
     ]
    },
    {
     "title": "P2P Latency",
     "type": "timeseries",
     "description": "# eth protocol\n\n- `0x00` = StatusMsg\n- `0x01` = NewBlockHashesMsg\n- `0x02` = TransactionsMsg\n- `0x03` = GetBlockHeadersMsg\n- `0x04` = BlockHeadersMsg\n- `0x05` = GetBlockBodiesMsg\n- `0x06` = BlockBodiesMsg\n- `0x07` = NewBlockMsg\n- `0x08` = NewPooledTransactionHashesMsg\n- `0x09` = GetPooledTransactionsMsg\n- `0x0a` = PooledTransactionsMsg\n- `0x0d` = GetNodeDataMsg\n- `0x0e` = NodeDataMsg\n- `0x0f` = GetReceiptsMsg\n- `0x10` = ReceiptsMsg\n\n# snap protocol\n\n- `0x00` = GetAccountRangeMsg\n- `0x01` = AccountRangeMsg\n- `0x02` = GetStorageRangesMsg\n- `0x03` = StorageRangesMsg\n- `0x04` = GetByteCodesMsg\n- `0x05` = ByteCodesMsg\n- `0x06` = GetTrieNodesMsg\n- `0x07` = TrieNodesMsg",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "label_replace(\n    label_replace({__name__=~\"p2p_handle_[a-z]+_[0-9]+_0x[0-9]+\", instance=~\"$instance\", quantile=\"$quantile\"}, \"protocol\", \"$1$2\", \"__name__\", \"p2p_handle_([a-z]+)_([0-9]+)_(0x[0-9]+)\"), \"msgcode\", \"$3\", \"__name__\", \"p2p_handle_([a-z]+)_([0-9]+)_(0x[0-9]+)\")",
       "legendFormat": "{{protocol}}-{{msgcode}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Downloader",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 155 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Throttle",
     "type": "stat",
     "description": "Measured in #peers per second",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(eth_downloader_throttle{chain=\"$chain\", instance=~\"$instance\"}[1m])"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "timeseries",
     "description": "Measured in blocks per second",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(eth_downloader_bodies_in{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "bodies in"
      },
      {
       "expr": "rate(eth_downloader_headers_in{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "headers in"
      },
      {
       "expr": "rate(eth_downloader_receipts_in{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "receipts in"
      }
     ]
    },
    {
     "title": "Abnormal QPS",
     "type": "timeseries",
     "description": "Measured in blocks per second",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "eth_downloader_bodies_drop{chain=\"$chain\", instance=~\"$instance\"}",
       "legendFormat": "bodies drop"
      },
      {
       "expr": "eth_downloader_headers_drop{chain=\"$chain\", instance=~\"$instance\"}",
       "legendFormat": "headers drop"
      },
      {
       "expr": "eth_downloader_receipts_drop{chain=\"$chain\", instance=~\"$instance\"}",
       "legendFormat": "receipts drop"
      },
      {
       "expr": "eth_downloader_bodies_timeout{chain=\"$chain\", instance=~\"$instance\"}",
       "legendFormat": "bodies timeout"
      },
      {
       "expr": "eth_downloader_headers_timeout{chain=\"$chain\", instance=~\"$instance\"}",
       "legendFormat": "headers timeout"
      },
      {
       "expr": "eth_downloader_receipts_timeout{chain=\"$chain\", instance=~\"$instance\"}",
       "legendFormat": "receipts timeout"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(eth_downloader_bodies_req{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}[1m])",
       "legendFormat": "bodies(q={{quantile}})"
      },
      {
       "expr": "rate(eth_downloader_headers_req{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}[1m])",
       "legendFormat": "headers(q={{quantile}})"
      },
      {
       "expr": "rate(eth_downloader_receipts_req{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}[1m])",
       "legendFormat": "receipts(q={{quantile}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Fetcher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 156 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Waiting Peers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "eth_fetcher_transaction_waiting_peers{chain=\"$chain\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Waiting Hashes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "eth_fetcher_transaction_waiting_hashes{chain=\"$chain\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Queueing Peers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "eth_fetcher_transaction_queueing_peers{chain=\"$chain\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Queueing Hashes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "eth_fetcher_transaction_queueing_hashes{chain=\"$chain\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Fetching Peers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "eth_fetcher_transaction_fetching_peers{chain=\"$chain\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Fetching Hashes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "eth_fetcher_transaction_fetching_hashes{chain=\"$chain\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "QPS of Transaction",
     "type": "timeseries",
     "description": "Measured in blocks per second",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(eth_fetcher_transaction_request_out{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "request out"
      },
      {
       "expr": "rate(eth_fetcher_transaction_request_fail{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "request fail"
      },
      {
       "expr": "rate(eth_fetcher_transaction_request_done{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "request done"
      },
      {
       "expr": "rate(eth_fetcher_transaction_request_timeout{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "request timeout"
      },
      {
       "expr": "rate(eth_fetcher_transaction_replies_in{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "replies in"
      },
      {
       "expr": "rate(eth_fetcher_transaction_replies_known{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "replies known"
      },
      {
       "expr": "rate(eth_fetcher_transaction_replies_underpriced{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "replies underpriced"
      },
      {
       "expr": "rate(eth_fetcher_transaction_replies_otherreject{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "replies otherreject"
      }
     ]
    },
    {
     "title": "QPS of Block",
     "type": "timeseries",
     "description": "Measured in blocks per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(eth_fetcher_block_bodies{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "bodies"
      },
      {
       "expr": "rate(eth_fetcher_block_headers{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "headers"
      },
      {
       "expr": "rate(eth_fetcher_block_filter_headers_in{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "filter headers in"
      },
      {
       "expr": "rate(eth_fetcher_block_filter_headers_out{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "filter headers out"
      },
      {
       "expr": "rate(eth_fetcher_block_filter_bodies_in{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "filter bodies in"
      },
      {
       "expr": "rate(eth_fetcher_block_filter_bodies_out{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "filter bodies out"
      }
     ]
    }
   ]
  },
  {
   "title": "Trie Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 157 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Clean cache-BPS",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(trie_memcache_clean_read{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "read"
      },
      {
       "expr": "rate(trie_memcache_clean_write{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Dirty cache-BPS",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(trie_memcache_gc_size{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "gc"
      },
      {
       "expr": "rate(trie_memcache_flush_size{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "overflow"
      },
      {
       "expr": "rate(trie_memcache_commit_size{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "commit"
      }
     ]
    },
    {
     "title": "Clean cache-Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      {
       "expr": "rate(trie_memcache_clean_hit{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "hit"
      },
      {
       "expr": "rate(trie_memcache_clean_miss{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "miss"
      },
      {
       "expr": "rate(trie_memcache_clean_hit{chain=\"$chain\", instance=~\"$instance\"}[1m])/(rate(trie_memcache_clean_miss{chain=\"$chain\", instance=~\"$instance\"}[1m])+rate(trie_memcache_clean_hit{chain=\"$chain\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "hit rate"
      }
     ]
    },
    {
     "title": "Dirty cache-Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      {
       "expr": "rate(trie_memcache_dirty_hit{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "hit"
      },
      {
       "expr": "rate(trie_memcache_dirty_miss{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "miss"
      },
      {
       "expr": "rate(trie_memcache_dirty_hit{chain=\"$chain\", instance=~\"$instance\"}[1m])/(rate(trie_memcache_dirty_miss{chain=\"$chain\", instance=~\"$instance\"}[1m])+rate(trie_memcache_dirty_hit{chain=\"$chain\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "hit rate"
      }
     ]
    },
    {
     "title": "MPT-Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "targets": [
      {
       "expr": "rate(trie_memcache_gc_nodes{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "gc"
      },
      {
       "expr": "rate(trie_memcache_commit_nodes{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "commit"
      },
      {
       "expr": "rate(trie_memcache_flush_nodes{chain=\"$chain\", instance=~\"$instance\"}[1m])",
       "legendFormat": "overflow"
      },
      {
       "expr": "trie_memcache_dirty_write{chain=\"$chain\", instance=~\"$instance\"} - trie_memcache_gc_size{chain=\"$chain\", instance=~\"$instance\"}",
       "legendFormat": "dirtysize"
      }
     ]
    },
    {
     "title": "MPT-Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(trie_memcache_gc_time{chain=\"$chain\", instance=~\"$instance\", quantile=~\"$quantile\"}[1m])",
       "legendFormat": "gc"
      },
      {
       "expr": "rate(trie_memcache_commit_time{chain=\"$chain\", instance=~\"$instance\", quantile=~\"$quantile\"}[1m])",
       "legendFormat": "commit"
      },
      {
       "expr": "rate(trie_memcache_flush_time{chain=\"$chain\", instance=~\"$instance\", quantile=~\"$quantile\"}[1m])",
       "legendFormat": "overflow"
      }
     ]
    }
   ]
  }
 ]
}