{
 "title": "Pebble Bench",
 "time": { "from": "2025-04-15T13:01:11.002Z", "to": "2025-04-15T19:05:45.578Z" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "disk",
    "label": "Disk",
    "query": {
     "query": "label_values(node_disk_info{instance=~\"$node\"},device)"
    }
   },
   {
    "name": "read_test",
    "label": "Read Test",
    "query": {
     "query": "label_values(read_count_total,test)"
    }
   },
   {
    "name": "write_test",
    "label": "Write Test",
    "query": {
     "query": "label_values(write_count_total,test)"
    }
   },
   {
    "name": "read_status",
    "label": "Read Status",
    "query": {
     "query": "label_values(read_count_total,status)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Benchmark",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Summary",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(read_count_total{}[$interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(write_count_total{}[$interval]))",
     "legendFormat": "Write"
    },
    { "expr": "pebble_disk_size", "legendFormat": "Disk Size" }
   ]
  },
  {
   "title": "Read Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(read_count_total{test=~\"$read_test\", status=~\"$read_status\"}[$interval]) > 0",
     "legendFormat": "{{test}}:{{status}}"
    }
   ]
  },
  {
   "title": "Write Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(write_count_total{}[$interval]) > 0",
     "legendFormat": "{{test}}"
    }
   ]
  },
  {
   "title": "Read Time",
   "type": "timeseries",
   "description": "Time spent on each read operation",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(read_seconds_total{test=~\"$read_test\", status=~\"$read_status\"}[$interval]) / rate(read_count_total{test=~\"$read_test\", status=~\"$read_status\"}[$interval]) > 0",
     "legendFormat": "{{test}}:{{status}}"
    }
   ]
  },
  {
   "title": "Write Time",
   "type": "timeseries",
   "description": "Time spent on each write operation",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(write_seconds_total{}[$interval]) / rate(write_count_total{}[$interval]) > 0",
     "legendFormat": "{{test}}"
    }
   ]
  },
  {
   "title": "Compact Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "rate(compact_count{}[1m])", "legendFormat": "count" },
    { "expr": "rate(compact_read_count{}[1m])", "legendFormat": "read" },
    { "expr": "rate(compact_move_count{}[1m])", "legendFormat": "move" },
    {
     "expr": "rate(compact_rewrite_count{}[1m])",
     "legendFormat": "rewrite"
    },
    {
     "expr": "rate(compact_multilevel_count{}[1m])",
     "legendFormat": "multilevel"
    },
    {
     "expr": "rate(compact_marked_files{}[1m])",
     "legendFormat": "marked files"
    }
   ]
  },
  {
   "title": "Compact ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(compact_estimated_debt{}[1m])",
     "legendFormat": "estimated debt"
    },
    { "expr": "rate(compact_duration{}[1m])", "legendFormat": "duration" }
   ]
  },
  {
   "title": "Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(read_bytes_total{test=~\"$read_test\"}[$interval])) by(test)",
     "legendFormat": "{{test}}_Read"
    }
   ]
  },
  {
   "title": "Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(write_bytes_total{}[$interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Disk IOps Completed（IOPS）",
   "type": "timeseries",
   "description": "Read/write completions per second\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=~\"$node\", device=~\"$disk\"}[$interval]) > 0 ",
     "legendFormat": "{{device}}_Reads completed"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=~\"$node\", device=~\"$disk\"}[$interval]) > 0",
     "legendFormat": "{{device}}_Writes completed"
    }
   ]
  },
  {
   "title": "Disk R/W Time",
   "type": "timeseries",
   "description": "Time spent on each read/write operation",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$node\", device=~\"$disk\"}[$interval]) / rate(node_disk_reads_completed_total{instance=~\"$node\", device=~\"$disk\"}[$interval])",
     "legendFormat": "{{device}}_Read time"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=~\"$node\", device=~\"$disk\"}[$interval]) / rate(node_disk_writes_completed_total{instance=~\"$node\", device=~\"$disk\"}[$interval])",
     "legendFormat": "{{device}}_Write time"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "timeseries",
   "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$node\", device=~\"$disk\"}[$interval]) > 0",
     "legendFormat": "{{device}}_ IO time"
    }
   ]
  },
  {
   "title": "CPU% Basic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[$interval])) by (instance) *100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[$interval])) by (instance) *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[$interval])) by (instance) *100",
     "legendFormat": "Iowait"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$interval])) by (instance))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "Avaliable"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "Used%"
    }
   ]
  },
  {
   "title": "Disk Space Used% Basic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "timeseries",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$node\", device=~\"$disk\"}[$interval])",
     "legendFormat": "{{device}}_Read bytes"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$node\", device=~\"$disk\"}[$interval])",
     "legendFormat": "{{device}}_Written bytes"
    }
   ]
  }
 ]
}